name: CloudPunish
version: '1.0'
main: cc.leafed.cloudpunish.CloudPunish
api-version: '1.20'
commands:
  punish:
    aliases: ["p"]
    description: Access the punishment system
    permission: cc.punishment
permissions:
  cc.punishment:
    default: op